In [38]:
import pandas as pd

In [55]:
base = pd.read_csv("01st Dec 2023.csv")

In [56]:
base.head()

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,502,503,504,505,506,507,508,509,510,511
0,0,-0.033767,-0.062013,0.065723,0.001536,0.050476,-0.055738,-0.022184,-0.012438,0.046424,...,-0.011513,-0.065541,0.018704,-0.040438,0.062275,-0.001694,0.050560,0.038943,-0.065725,-0.063248
1,1,0.006280,-0.053006,-0.026932,0.025895,0.060540,-0.055329,0.059298,0.011653,-0.028104,...,-0.060365,-0.070879,-0.031699,-0.028010,0.024317,-0.053369,-0.010466,0.011693,0.070882,0.023400
2,2,-0.001477,-0.055337,-0.007228,0.012120,-0.019200,0.062914,0.025323,-0.066566,0.072108,...,0.036587,-0.083069,0.049554,0.039093,-0.054031,0.064956,0.053276,-0.000894,0.084186,-0.030582
3,3,-0.051222,-0.003772,-0.020266,-0.051336,0.040837,0.056242,-0.044103,-0.003871,0.042286,...,-0.070430,-0.075139,0.048950,0.035363,-0.032137,0.032177,0.042134,0.050571,0.064094,0.027933
4,4,-0.015625,-0.025217,-0.037066,0.055000,0.043866,0.052134,0.050531,-0.012746,0.034521,...,-0.050129,-0.072009,0.055693,0.032744,-0.069008,-0.019234,0.036535,-0.021147,0.072013,0.053650

In [57]:
base.shape

(10000, 513)

In [58]:
new_df = base.iloc[:1000]

In [59]:
new_df.to_csv("smaller_01st Dec 2023.csv")

In [60]:
import os

In [76]:
df = pd.read_csv("New/baseline_paths_df.csv")

In [77]:
df.head()

                                               paths    target
0  C:/Users/Akshat Mittu/Desktop/Model Monitoring...  fracture
1  C:/Users/Akshat Mittu/Desktop/Model Monitoring...  fracture
2  C:/Users/Akshat Mittu/Desktop/Model Monitoring...  fracture
3  C:/Users/Akshat Mittu/Desktop/Model Monitoring...  fracture
4  C:/Users/Akshat Mittu/Desktop/Model Monitoring...  fracture

In [78]:
"." + df.iloc[0]['paths'].split("Model Monitoring Dashboard")[1]

'./pages/models/Bone Fracture Detection/Baseline/fracture/10-rotated1-rotated1-rotated1.jpg'

In [79]:
def change_paths(i):
    return "." + i.split("Model Monitoring Dashboard")[1]

In [80]:
change_paths(df.iloc[0]['paths'])

'./pages/models/Bone Fracture Detection/Baseline/fracture/10-rotated1-rotated1-rotated1.jpg'

In [81]:
df['paths'] = df['paths'].apply(change_paths)

In [82]:
df['paths']

0       ./pages/models/Bone Fracture Detection/Baselin...
1       ./pages/models/Bone Fracture Detection/Baselin...
2       ./pages/models/Bone Fracture Detection/Baselin...
3       ./pages/models/Bone Fracture Detection/Baselin...
4       ./pages/models/Bone Fracture Detection/Baselin...
                              ...
1211    ./pages/models/Bone Fracture Detection/Baselin...
1212    ./pages/models/Bone Fracture Detection/Baselin...
1213    ./pages/models/Bone Fracture Detection/Baselin...
1214    ./pages/models/Bone Fracture Detection/Baselin...
1215    ./pages/models/Bone Fracture Detection/Baselin...
Name: paths, Length: 1216, dtype: object

In [83]:
df.head()

                                               paths    target
0  ./pages/models/Bone Fracture Detection/Baselin...  fracture
1  ./pages/models/Bone Fracture Detection/Baselin...  fracture
2  ./pages/models/Bone Fracture Detection/Baselin...  fracture
3  ./pages/models/Bone Fracture Detection/Baselin...  fracture
4  ./pages/models/Bone Fracture Detection/Baselin...  fracture

In [84]:
df.to_csv("changed_baseline_paths_df.csv")